#!/usr/bin/env bash

brew update
echo "Install Docker with Docker Toolbox at https://www.docker.com/docker-toolbox"
brew install jq
brew install tmux
brew install htop-osx
brew install ack
brew install pyenv
