#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y ack-grep
sudo apt-get install -y docker
sudo apt-get install -y docker-compose
sudo apt-get install -y docker-machine
sudo apt-get install -y emacs
sudo apt-get install -y htop
sudo apt-get install -y jq
sudo apt-get install -y sbcl
sudo apt-get install -y tmux
sudo apt-get install -y vim
sudo apt-get install -y pyenv 
# pyenv post processing
if [ ! -e /Users/juys/.pyenv/plugins/pyenv-virtualenv ] ; then
  mkdir -p ~/.pyenv/plugins
  git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
fi

